package com.google.android.gms.internal;

import android.content.Context;
import android.content.SharedPreferences.Editor;
import android.support.v7.widget.helper.ItemTouchHelper.Callback;
import com.google.android.gms.ads.internal.zzbv;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.json.JSONObject;

@aqv
public final class ado {
    public static final ade<Integer> f4862A = ade.m4191a(1, "gads:video:codec_query_minimum_version", 16);
    public static final ade<Boolean> f4863B = ade.m4193a(0, "gads:looper_for_gms_client:enabled", Boolean.valueOf(true));
    public static final ade<Boolean> f4864C = ade.m4193a(0, "gads:sw_ad_request_service:enabled", Boolean.valueOf(true));
    public static final ade<String> f4865D = ade.m4194a(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    public static final ade<String> f4866E = ade.m4194a(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    public static final ade<String> f4867F = ade.m4194a(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    public static final ade<Boolean> f4868G = ade.m4193a(0, "gads:enabled_sdk_csi", Boolean.valueOf(false));
    public static final ade<String> f4869H = ade.m4194a(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    public static final ade<Boolean> f4870I = ade.m4193a(0, "gads:sdk_csi_write_to_file", Boolean.valueOf(false));
    public static final ade<Boolean> f4871J = ade.m4193a(0, "gads:enable_content_fetching", Boolean.valueOf(true));
    public static final ade<Integer> f4872K = ade.m4191a(0, "gads:content_length_weight", 1);
    public static final ade<Integer> f4873L = ade.m4191a(0, "gads:content_age_weight", 1);
    public static final ade<Integer> f4874M = ade.m4191a(0, "gads:min_content_len", 11);
    public static final ade<Integer> f4875N = ade.m4191a(0, "gads:fingerprint_number", 10);
    public static final ade<Integer> f4876O = ade.m4191a(0, "gads:sleep_sec", 10);
    public static final ade<Boolean> f4877P = ade.m4193a(1, "gads:enable_content_url_hash", Boolean.valueOf(true));
    public static final ade<Integer> f4878Q = ade.m4191a(1, "gads:content_vertical_fingerprint_number", 100);
    public static final ade<Boolean> f4879R = ade.m4193a(1, "gads:enable_content_vertical_hash", Boolean.valueOf(true));
    public static final ade<Integer> f4880S = ade.m4191a(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final ade<Integer> f4881T = ade.m4191a(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final ade<String> f4882U = ade.m4194a(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final ade<String> f4883V = ade.m4194a(1, "gads:content_fetch_exclude_view_tag", "none");
    public static final ade<Boolean> f4884W = ade.m4193a(0, "gad:app_index_enabled", Boolean.valueOf(true));
    public static final ade<Boolean> f4885X = ade.m4193a(1, "gads:content_fetch_disable_get_title_from_webview", Boolean.valueOf(false));
    public static final ade<Boolean> f4886Y = ade.m4193a(0, "gads:app_index:without_content_info_present:enabled", Boolean.valueOf(true));
    public static final ade<Long> f4887Z = ade.m4192a(0, "gads:app_index:timeout_ms", 1000);
    public static final ade<String> f4888a = ade.m4194a(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    public static final ade<Boolean> aA = ade.m4193a(1, "gads:enable_ad_loader_manager", Boolean.valueOf(true));
    public static final ade<Boolean> aB = ade.m4193a(1, "gads:ad_manager_enforce_arp_invariant:enabled", Boolean.valueOf(false));
    public static final ade<Long> aC = ade.m4192a(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000);
    public static final ade<Boolean> aD = ade.m4193a(1, "gads:interstitial_ad_immersive_mode", Boolean.valueOf(true));
    public static final ade<Boolean> aE = ade.m4193a(1, "gads:interstitial_ad_pool:enabled", Boolean.valueOf(false));
    public static final ade<Boolean> aF = ade.m4193a(1, "gads:interstitial_ad_pool:enabled_for_rewarded", Boolean.valueOf(false));
    public static final ade<String> aG = ade.m4194a(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    public static final ade<String> aH = ade.m4194a(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    public static final ade<Integer> aI = ade.m4191a(1, "gads:interstitial_ad_pool:max_pools", 3);
    public static final ade<Integer> aJ = ade.m4191a(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    public static final ade<Integer> aK = ade.m4191a(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    public static final ade<String> aL = ade.m4194a(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    public static final ade<Integer> aM = ade.m4191a(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    public static final ade<Integer> aN = ade.m4191a(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    public static final ade<Long> aO = ade.m4192a(1, "gads:interstitial_ad_pool:discard_thresholds", 0);
    public static final ade<Long> aP = ade.m4192a(1, "gads:interstitial_ad_pool:miss_thresholds", 0);
    public static final ade<Float> aQ = ade.m4190a(1, "gads:interstitial_ad_pool:discard_asymptote");
    public static final ade<Float> aR = ade.m4190a(1, "gads:interstitial_ad_pool:miss_asymptote");
    public static final ade<String> aS = ade.m4194a(1, "gads:spherical_video:vertex_shader", "");
    public static final ade<String> aT = ade.m4194a(1, "gads:spherical_video:fragment_shader", "");
    public static final ade<Boolean> aU = ade.m4193a(0, "gads:log:verbose_enabled", Boolean.valueOf(false));
    public static final ade<Boolean> aV = ade.m4193a(1, "gads:include_local_global_rectangles", Boolean.valueOf(false));
    public static final ade<Long> aW = ade.m4192a(1, "gads:position_watcher:throttle_ms", 200);
    public static final ade<Boolean> aX = ade.m4193a(1, "gads:include_lock_screen_apps_for_visibility", Boolean.valueOf(true));
    public static final ade<Boolean> aY = ade.m4193a(0, "gads:device_info_caching:enabled", Boolean.valueOf(true));
    public static final ade<Long> aZ = ade.m4192a(0, "gads:device_info_caching_expiry_ms:expiry", 300000);
    public static final ade<Boolean> aa = ade.m4193a(0, "gads:kitkat_interstitial_workaround:enabled", Boolean.valueOf(true));
    public static final ade<Boolean> ab = ade.m4193a(0, "gads:interstitial_follow_url", Boolean.valueOf(true));
    public static final ade<Boolean> ac = ade.m4193a(0, "gads:interstitial_follow_url:register_click", Boolean.valueOf(true));
    public static final ade<Boolean> ad = ade.m4193a(0, "gads:ad_key_enabled", Boolean.valueOf(false));
    public static final ade<Boolean> ae = ade.m4193a(1, "gads:sai:enabled", Boolean.valueOf(false));
    public static final ade<Boolean> af = ade.m4193a(1, "gads:sai:banner_ad_enabled", Boolean.valueOf(true));
    public static final ade<Boolean> ag = ade.m4193a(1, "gads:sai:native_ad_enabled", Boolean.valueOf(true));
    public static final ade<Boolean> ah = ade.m4193a(1, "gads:sai:interstitial_ad_enabled", Boolean.valueOf(true));
    public static final ade<Boolean> ai = ade.m4193a(1, "gads:sai:rewardedvideo_ad_enabled", Boolean.valueOf(true));
    public static final ade<String> aj = ade.m4194a(1, "gads:sai:click_ping_schema", "[\"/aclk\",\"/pcs/click\"]");
    public static final ade<String> ak = ade.m4194a(1, "gads:sai:impression_ping_schema", "[\"/adview\"]");
    public static final ade<Boolean> al = ade.m4193a(1, "gads:sai:click_gmsg_enabled", Boolean.valueOf(true));
    public static final ade<Boolean> am = ade.m4193a(1, "gads:sai:using_macro:enabled", Boolean.valueOf(false));
    public static final ade<String> an = ade.m4194a(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    public static final ade<Long> ao = ade.m4192a(1, "gads:sai:timeout_ms", 100);
    public static final ade<Integer> ap = ade.m4191a(1, "gads:sai:scion_thread_pool_size", 5);
    public static final ade<Boolean> aq = ade.m4193a(1, "gads:webview_recycle:enabled", Boolean.valueOf(false));
    public static final ade<Boolean> ar = ade.m4193a(1, "gads:webview:ignore_over_scroll", Boolean.valueOf(true));
    public static final ade<Boolean> as = ade.m4193a(1, "gads:rewarded:adapter_initialization_enabled", Boolean.valueOf(false));
    public static final ade<Long> at = ade.m4192a(1, "gads:rewarded:adapter_timeout_ms", 20000);
    public static final ade<Boolean> au = ade.m4193a(1, "gads:app_activity_tracker:enabled", Boolean.valueOf(true));
    public static final ade<Long> av = ade.m4192a(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
    public static final ade<Long> aw = ade.m4192a(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final ade<Boolean> ax = ade.m4193a(1, "gads:adid_values_in_adrequest:enabled", Boolean.valueOf(false));
    public static final ade<Long> ay = ade.m4192a(1, "gads:adid_values_in_adrequest:timeout", 2000);
    public static final ade<Boolean> az = ade.m4193a(1, "gads:disable_adid_values_in_ms", Boolean.valueOf(false));
    public static final ade<Boolean> f4889b = ade.m4193a(0, "gads:sdk_crash_report_enabled", Boolean.valueOf(false));
    public static final ade<Boolean> bA = ade.m4193a(0, "gass:enabled", Boolean.valueOf(true));
    public static final ade<Boolean> bB = ade.m4193a(0, "gass:enable_int_signal", Boolean.valueOf(true));
    public static final ade<Boolean> bC = ade.m4193a(0, "gass:enable_ad_attestation_signal", Boolean.valueOf(true));
    public static final ade<Boolean> bD = ade.m4193a(0, "gads:support_screen_shot", Boolean.valueOf(true));
    public static final ade<Boolean> bE = ade.m4193a(0, "gads:use_get_drawing_cache_for_screenshot:enabled", Boolean.valueOf(true));
    public static final ade<String> bF = ade.m4194a(1, "gads:sdk_core_constants:caps", "");
    public static final ade<Long> bG = ade.m4192a(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
    public static final ade<Boolean> bH = ade.m4193a(0, "gads:js_flags:mf", Boolean.valueOf(false));
    public static final ade<Boolean> bI = ade.m4193a(0, "gads:custom_render:ping_on_ad_rendered", Boolean.valueOf(false));
    public static final ade<String> bJ = ade.m4194a(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    public static final ade<String> bK = ade.m4194a(1, "gads:native:video_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_video_ads.html");
    public static final ade<Boolean> bL = ade.m4193a(1, "gads:singleton_webview_native", Boolean.valueOf(false));
    public static final ade<Boolean> bM = ade.m4193a(1, "gads:native_initialize_webview_request_time", Boolean.valueOf(false));
    public static final ade<Boolean> bN = ade.m4193a(1, "gads:enable_untrack_view_native", Boolean.valueOf(true));
    public static final ade<Boolean> bO = ade.m4193a(1, "gads:ignore_untrack_view_google_native", Boolean.valueOf(true));
    public static final ade<Boolean> bP = ade.m4193a(1, "gads:reset_listeners_preparead_native", Boolean.valueOf(true));
    public static final ade<Integer> bQ = ade.m4191a(1, "gads:native_video_load_timeout", 10);
    public static final ade<String> bR = ade.m4194a(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    public static final ade<Boolean> bS = ade.m4193a(1, "gads:clamp_native_video_player_dimensions", Boolean.valueOf(true));
    public static final ade<Boolean> bT = ade.m4193a(1, "gads:enable_store_active_view_state", Boolean.valueOf(false));
    public static final ade<Integer> bU = ade.m4191a(1, "gads:max_number_of_native_ads_allowed", 5);
    public static final ade<Boolean> bV = ade.m4193a(1, "gads:fluid_ad:use_wrap_content_height", Boolean.valueOf(false));
    public static final ade<Boolean> bW = ade.m4193a(0, "gads:method_tracing:enabled", Boolean.valueOf(false));
    public static final ade<Long> bX = ade.m4192a(0, "gads:method_tracing:duration_ms", 30000);
    public static final ade<Integer> bY = ade.m4191a(0, "gads:method_tracing:count", 5);
    public static final ade<Integer> bZ = ade.m4191a(0, "gads:method_tracing:filesize", 134217728);
    public static final ade<Boolean> ba = ade.m4193a(0, "gads:gen204_signals:enabled", Boolean.valueOf(false));
    public static final ade<Boolean> bb = ade.m4193a(0, "gads:webview:error_reporting_enabled", Boolean.valueOf(false));
    public static final ade<Boolean> bc = ade.m4193a(1, "gads:gmsg:disable_back_button:enabled", Boolean.valueOf(true));
    public static final ade<Boolean> bd = ade.m4193a(0, "gads:gmsg:video_meta:enabled", Boolean.valueOf(true));
    public static final ade<Long> be = ade.m4192a(1, "gads:network:network_prediction_timeout_ms", 2000);
    public static final ade<Boolean> bf = ade.m4193a(0, "gads:mediation:dynamite_first:admobadapter", Boolean.valueOf(true));
    public static final ade<Boolean> bg = ade.m4193a(0, "gads:mediation:dynamite_first:adurladapter", Boolean.valueOf(true));
    public static final ade<Boolean> bh = ade.m4193a(1, "gads:bypass_adrequest_service_for_inlined_mediation", Boolean.valueOf(true));
    public static final ade<Long> bi = ade.m4192a(0, "gads:resolve_future:default_timeout_ms", 30000);
    public static final ade<Long> bj = ade.m4192a(0, "gads:ad_loader:timeout_ms", 60000);
    public static final ade<Long> bk = ade.m4192a(0, "gads:rendering:timeout_ms", 60000);
    public static final ade<Boolean> bl = ade.m4193a(0, "gads:adshield:enable_adshield_instrumentation", Boolean.valueOf(false));
    public static final ade<Long> bm = ade.m4192a(1, "gads:gestures:task_timeout", 2000);
    public static final ade<Boolean> bn = ade.m4193a(1, "gads:gestures:encrypt_size_limit:enabled", Boolean.valueOf(false));
    public static final ade<Boolean> bo = ade.m4193a(1, "gads:gestures:orn_caching:enabled", Boolean.valueOf(true));
    public static final ade<Boolean> bp = ade.m4193a(1, "gads:gestures:oc:enabled", Boolean.valueOf(false));
    public static final ade<Integer> bq = ade.m4191a(1, "gads:gestures:ts", 1);
    public static final ade<Boolean> br = ade.m4193a(1, "gads:gestures:td:enabled", Boolean.valueOf(false));
    public static final ade<Boolean> bs = ade.m4193a(1, "gads:gestures:tdvs:enabled", Boolean.valueOf(false));
    public static final ade<Boolean> bt = ade.m4193a(1, "gads:gestures:tuvs:enabled", Boolean.valueOf(false));
    public static final ade<Boolean> bu = ade.m4193a(1, "gads:gestures:tvvs:enabled", Boolean.valueOf(false));
    public static final ade<Boolean> bv = ade.m4193a(1, "gads:gestures:vd:enabled", Boolean.valueOf(false));
    public static final ade<String> bw = ade.m4194a(1, "gads:gestures:pk", "");
    public static final ade<Boolean> bx = ade.m4193a(1, "gads:gestures:bs:enabled", Boolean.valueOf(true));
    public static final ade<Boolean> by = ade.m4193a(1, "gads:gestures:check_initialization_thread:enabled", Boolean.valueOf(false));
    public static final ade<Boolean> bz = ade.m4193a(1, "gads:gestures:get_query_in_non_ui_thread:enabled", Boolean.valueOf(true));
    public static final ade<Boolean> f4890c = ade.m4193a(0, "gads:sdk_crash_report_full_stacktrace", Boolean.valueOf(false));
    public static final ade<Integer> cA = ade.m4191a(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final ade<Boolean> cB = ade.m4193a(1, "gad:interstitial_for_multi_window", Boolean.valueOf(false));
    public static final ade<Boolean> cC = ade.m4193a(1, "gad:interstitial_ad_stay_active_in_multi_window", Boolean.valueOf(false));
    public static final ade<Integer> cD = ade.m4191a(1, "gad:interstitial:close_button_padding_dip", 0);
    public static final ade<Boolean> cE = ade.m4193a(1, "gads:clearcut_logging:enabled", Boolean.valueOf(false));
    public static final ade<Integer> cF = ade.m4191a(1, "gads:clearcut_messageTime:ms", 60000);
    public static final ade<Boolean> cG = ade.m4193a(0, "gad:force_local_ad_request_service:enabled", Boolean.valueOf(false));
    public static final ade<Integer> cH = ade.m4191a(1, "gad:http_redirect_max_count:times", 8);
    public static final ade<Long> cI = ade.m4192a(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000);
    private static ade<String> cJ = ade.m4195b(0, "gads:sdk_core_experiment_id");
    private static ade<Boolean> cK = ade.m4193a(0, "gads:request_builder:singleton_webview", Boolean.valueOf(false));
    private static ade<String> cL = ade.m4195b(0, "gads:request_builder:singleton_webview_experiment_id");
    private static ade<Boolean> cM = ade.m4193a(0, "gads:sdk_use_dynamic_module", Boolean.valueOf(true));
    private static ade<String> cN = ade.m4195b(0, "gads:sdk_use_dynamic_module_experiment_id");
    private static ade<String> cO = ade.m4195b(0, "gads:block_autoclicks_experiment_id");
    private static ade<String> cP = ade.m4195b(0, "gads:spam_app_context:experiment_id");
    private static ade<Integer> cQ = ade.m4191a(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    private static ade<String> cR = ade.m4195b(0, "gads:video_stream_cache:experiment_id");
    private static ade<Boolean> cS = ade.m4193a(0, "gads:ad_id_app_context:enabled", Boolean.valueOf(false));
    private static ade<Float> cT = ade.m4190a(0, "gads:ad_id_app_context:ping_ratio");
    private static ade<String> cU = ade.m4195b(0, "gads:ad_id_app_context:experiment_id");
    private static ade<String> cV = ade.m4195b(0, "gads:ad_id_use_shared_preference:experiment_id");
    private static ade<Boolean> cW = ade.m4193a(0, "gads:ad_id_use_shared_preference:enabled", Boolean.valueOf(false));
    private static ade<Float> cX = ade.m4190a(0, "gads:ad_id_use_shared_preference:ping_ratio");
    private static ade<String> cY = ade.m4196c(0, "gads:looper_for_gms_client:experiment_id");
    private static ade<Boolean> cZ = ade.m4193a(0, "gads:sw_dynamite:enabled", Boolean.valueOf(true));
    public static final ade<Long> ca = ade.m4192a(1, "gads:auto_location_timeout", 2000);
    public static final ade<Boolean> cb = ade.m4193a(1, "gads:fetch_app_settings_using_cld:enabled", Boolean.valueOf(false));
    public static final ade<Long> cc = ade.m4192a(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
    public static final ade<String> cd = ade.m4194a(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    public static final ade<String> ce = ade.m4194a(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    public static final ade<String> cf = ade.m4194a(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    public static final ade<String> cg = ade.m4194a(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    public static final ade<String> ch = ade.m4194a(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    public static final ade<Long> ci = ade.m4192a(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000);
    public static final ade<Long> cj = ade.m4192a(1, "gads:parental_controls:timeout", 2000);
    public static final ade<Boolean> ck = ade.m4193a(0, "gads:safe_browsing:debug", Boolean.valueOf(false));
    public static final ade<Boolean> cl = ade.m4193a(0, "gads:webview_cookie:enabled", Boolean.valueOf(true));
    public static final ade<Boolean> cm = ade.m4193a(1, "gads:cache:bind_on_foreground", Boolean.valueOf(false));
    public static final ade<Boolean> cn = ade.m4193a(1, "gads:cache:bind_on_init", Boolean.valueOf(false));
    public static final ade<Boolean> co = ade.m4193a(1, "gads:cache:bind_on_request", Boolean.valueOf(false));
    public static final ade<Long> cp = ade.m4192a(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    public static final ade<Boolean> cq = ade.m4193a(1, "gads:chrome_custom_tabs:enabled", Boolean.valueOf(true));
    public static final ade<Boolean> cr = ade.m4193a(1, "gads:chrome_custom_tabs_browser:enabled", Boolean.valueOf(false));
    public static final ade<Boolean> cs = ade.m4193a(1, "gads:chrome_custom_tabs:disabled", Boolean.valueOf(false));
    public static final ade<Boolean> ct = ade.m4193a(1, "gads:drx_in_app_preview:enabled", Boolean.valueOf(true));
    public static final ade<Boolean> cu = ade.m4193a(1, "gads:drx_debug_signals:enabled", Boolean.valueOf(true));
    public static final ade<String> cv = ade.m4194a(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final ade<String> cw = ade.m4194a(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final ade<String> cx = ade.m4194a(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final ade<String> cy = ade.m4194a(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final ade<Integer> cz = ade.m4191a(1, "gads:drx_debug:timeout_ms", 5000);
    public static final ade<String> f4891d = ade.m4194a(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    private static ade<String> dA = ade.m4196c(1, "gads:auto_location_for_coarse_permission:experiment_id");
    private static ade<String> dB = ade.m4196c(1, "gads:auto_location_timeout:experiment_id");
    private static ade<Long> dC = ade.m4192a(1, "gads:auto_location_interval", -1);
    private static ade<String> dD = ade.m4196c(1, "gads:auto_location_interval:experiment_id");
    private static ade<String> dE = ade.m4195b(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    private static ade<String> dF = ade.m4195b(0, "gads:afs:csa:experiment_id");
    private static ade<Boolean> dG = ade.m4193a(0, "gads:afs:csa_ad_manager_enabled", Boolean.valueOf(true));
    private static ade<Boolean> dH = ade.m4193a(1, "gads:parental_controls:send_from_client", Boolean.valueOf(true));
    private static ade<Boolean> dI = ade.m4193a(1, "gads:parental_controls:cache_results", Boolean.valueOf(true));
    private static ade<String> dJ = ade.m4194a(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    private static ade<Long> dK = ade.m4192a(0, "gads:safe_browsing:safety_net:delay_ms", 2000);
    private static ade<Integer> dL = ade.m4191a(1, "gads:cache:ad_request_timeout_millis", (int) Callback.DEFAULT_SWIPE_ANIMATION_DURATION);
    private static ade<Integer> dM = ade.m4191a(1, "gads:cache:max_concurrent_downloads", 10);
    private static ade<Long> dN = ade.m4192a(1, "gads:cache:javascript_timeout_millis", 5000);
    private static ade<Boolean> dO = ade.m4193a(1, "gads:cache:use_cache_data_source", Boolean.valueOf(false));
    private static ade<Boolean> dP = ade.m4193a(1, "gads:cache:connection_per_read", Boolean.valueOf(false));
    private static ade<Long> dQ = ade.m4192a(1, "gads:cache:connection_timeout", 5000);
    private static ade<Long> dR = ade.m4192a(1, "gads:cache:read_only_connection_timeout", 5000);
    private static ade<Boolean> dS = ade.m4193a(1, "gads:clearcut_abtest:enabled", Boolean.valueOf(false));
    private static ade<Boolean> dT = ade.m4193a(0, "gads:nonagon:red_button", Boolean.valueOf(false));
    private static ade<Boolean> dU = ade.m4193a(1, "gads:nonagon:banner:enabled", Boolean.valueOf(false));
    private static ade<String> dV = ade.m4194a(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
    private static ade<Boolean> dW = ade.m4193a(1, "gads:nonagon:interstitial:enabled", Boolean.valueOf(false));
    private static ade<String> dX = ade.m4194a(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
    private static ade<Boolean> dY = ade.m4193a(1, "gads:nonagon:rewardedvideo:enabled", Boolean.valueOf(false));
    private static ade<String> dZ = ade.m4194a(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
    private static ade<String> da = ade.m4195b(0, "gads:app_index:experiment_id");
    private static ade<String> db = ade.m4195b(0, "gads:kitkat_interstitial_workaround:experiment_id");
    private static ade<String> dc = ade.m4195b(0, "gads:interstitial_follow_url:experiment_id");
    private static ade<Boolean> dd = ade.m4193a(0, "gads:analytics_enabled", Boolean.valueOf(true));
    private static ade<Integer> de = ade.m4191a(0, "gads:webview_cache_version", 0);
    private static ade<String> df = ade.m4196c(0, "gads:pan:experiment_id");
    private static ade<Boolean> dg = ade.m4193a(0, "gads:ad_serving:enabled", Boolean.valueOf(true));
    private static ade<Boolean> dh = ade.m4193a(1, "gads:impression_optimization_enabled", Boolean.valueOf(false));
    private static ade<String> di = ade.m4194a(1, "gads:banner_ad_pool:schema", "customTargeting");
    private static ade<Integer> dj = ade.m4191a(1, "gads:banner_ad_pool:max_queues", 3);
    private static ade<Integer> dk = ade.m4191a(1, "gads:banner_ad_pool:max_pools", 3);
    private static ade<Integer> dl = ade.m4191a(1, "gads:heap_wastage:bytes", 0);
    private static ade<Boolean> dm = ade.m4193a(0, "gads:adid_reporting:enabled", Boolean.valueOf(false));
    private static ade<Boolean> dn = ade.m4193a(0, "gads:ad_settings_page_reporting:enabled", Boolean.valueOf(false));
    private static ade<Boolean> f4892do = ade.m4193a(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", Boolean.valueOf(false));
    private static ade<Boolean> dp = ade.m4193a(0, "gads:request_pkg:enabled", Boolean.valueOf(true));
    private static ade<String> dq = ade.m4195b(0, "gads:gmsg:video_meta:experiment_id");
    private static ade<Long> dr = ade.m4192a(1, "gads:network:cache_prediction_duration_s", 300);
    private static ade<Boolean> ds = ade.m4193a(0, "gads:adid_notification:first_party_check:enabled", Boolean.valueOf(true));
    private static ade<Boolean> dt = ade.m4193a(0, "gads:edu_device_helper:enabled", Boolean.valueOf(true));
    private static ade<String> du = ade.m4195b(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
    private static ade<String> dv = ade.m4195b(1, "gads:sdk_core_constants:experiment_id");
    private static ade<String> dw = ade.m4194a(0, "gads:native:engine_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    private static ade<String> dx = ade.m4194a(1, "gads:native:video_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_video_ads.html");
    private static ade<String> dy = ade.m4195b(1, "gads:singleton_webview_native:experiment_id");
    private static ade<Boolean> dz = ade.m4193a(1, "gads:auto_location_for_coarse_permission", Boolean.valueOf(false));
    public static final ade<Boolean> f4893e = ade.m4193a(0, "gads:block_autoclicks", Boolean.valueOf(false));
    private static ade<Boolean> ea = ade.m4193a(1, "gads:nonagon:service:enabled", Boolean.valueOf(false));
    private static byte[] eb;
    public static final ade<Boolean> f4894f = ade.m4193a(1, "gads:spam_app_context:enabled", Boolean.valueOf(false));
    public static final ade<String> f4895g = ade.m4194a(1, "gads:video_exo_player:version", "1");
    public static final ade<Integer> f4896h = ade.m4191a(1, "gads:video_stream_cache:limit_count", 5);
    public static final ade<Integer> f4897i = ade.m4191a(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final ade<Integer> f4898j = ade.m4191a(1, "gads:video_stream_exo_allocator:segment_size", 65536);
    public static final ade<Integer> f4899k = ade.m4191a(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final ade<Long> f4900l = ade.m4192a(1, "gads:video_stream_cache:limit_time_sec", 300);
    public static final ade<Long> f4901m = ade.m4192a(1, "gads:video_stream_cache:notify_interval_millis", 125);
    public static final ade<Integer> f4902n = ade.m4191a(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final ade<Boolean> f4903o = ade.m4193a(0, "gads:video:metric_reporting_enabled", Boolean.valueOf(false));
    public static final ade<String> f4904p = ade.m4194a(1, "gads:video:metric_frame_hash_times", "");
    public static final ade<Long> f4905q = ade.m4192a(1, "gads:video:metric_frame_hash_time_leniency", 500);
    public static final ade<Boolean> f4906r = ade.m4193a(1, "gads:video:force_watermark", Boolean.valueOf(false));
    public static final ade<Long> f4907s = ade.m4192a(1, "gads:video:surface_update_min_spacing_ms", 1000);
    public static final ade<Boolean> f4908t = ade.m4193a(1, "gads:video:spinner:enabled", Boolean.valueOf(false));
    public static final ade<Integer> f4909u = ade.m4191a(1, "gads:video:spinner:scale", 4);
    public static final ade<Long> f4910v = ade.m4192a(1, "gads:video:spinner:jank_threshold_ms", 50);
    public static final ade<Boolean> f4911w = ade.m4193a(1, "gads:video:aggressive_media_codec_release", Boolean.valueOf(false));
    public static final ade<Boolean> f4912x = ade.m4193a(1, "gads:memory_bundle:debug_info", Boolean.valueOf(false));
    public static final ade<Boolean> f4913y = ade.m4193a(1, "gads:memory_bundle:runtime_info", Boolean.valueOf(true));
    public static final ade<String> f4914z = ade.m4194a(1, "gads:video:codec_query_mime_types", "");

    public static List<String> m4218a() {
        return zzbv.zzem().m4215a();
    }

    public static void m4219a(Context context) {
        ht.m5600a(new adp(context));
        int intValue = ((Integer) zzbv.zzen().m4217a(dl)).intValue();
        if (intValue > 0 && eb == null) {
            eb = new byte[intValue];
        }
    }

    public static void m4220a(Context context, JSONObject jSONObject) {
        zzbv.zzel();
        Editor edit = context.getSharedPreferences("google_ads_flags", 0).edit();
        zzbv.zzem().m4216a(edit, jSONObject);
        zzbv.zzel();
        edit.commit();
    }

    public static List<String> m4221b() {
        adk zzem = zzbv.zzem();
        List<String> a = zzem.m4215a();
        for (ade a2 : zzem.f4855c) {
            String str = (String) zzbv.zzen().m4217a(a2);
            if (str != null) {
                a.add(str);
            }
        }
        return a;
    }
}
